### ISSUE TITLE
Raspberry Pi Simultaneous AP and Managed (Client) Mode WiFi

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#111]
https://news.ycombinator.com/item?id=15351778

**Comment by i5o** [comment]
> https://albeec13.github.io/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/

**Comment by i5o** [comment]
detect if rpi zero an add g_ether to /boot/cmdline
