### ISSUE TITLE
on rpi 3b+ wifi is disabled

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#247]
```
Wi-Fi is disabled because the country is not set.
Use raspi-config to set the country before use.
```

Should we create a pirateship/treehouses command to deal with it?

**Comment by i5o** [comment]
I'll rather at the country at the moment we run pirateship wifi.

where do you see this error btw?
(screenshots are welcome)

**Comment by dogi** [comment]
at login ;)

**Comment by i5o** [comment]
are we going to keep updating pirateship once treehouses cli is done?

**Comment by i5o** [comment]
https://github.com/RPi-Distro/raspi-config/blob/0c055b6ab7a713a73ce9103c257521d86f88ff4a/raspi-config#L430
