### ISSUE TITLE
update clonepi script to work with dev.ole.org

### ISSUE THREAD

**Issue by 0xdaf** [treehouses/builder#38]

**Comment by 0xdaf** [comment]
old/current script is at https://github.com/dogi/pirateship--pirateship-image

**Comment by dogi** [comment]
todo:
- [ ] https://github.com/ole-vi/treehouse--treehouse-image
- [ ] README.md needs to be fixed

vision:
- boot maybe from USB massstorage ;)
- use now spared microsdcard slots to make images
- overtact that slot ala https://www.pidramble.com/wiki/benchmarks/microsd-cards
