### ISSUE TITLE
fix broken balena

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#428]
https://travis-ci.org/treehouses/builder/builds/512264993#L2105

**Comment by i5o** [comment]
reopening:
https://github.com/balena-os/balena-engine/issues/156#issuecomment-482110380

**Comment by dogi** [comment]
@i5o should we close this but open a new issue ?

**Comment by i5o** [comment]
let me check

**Comment by i5o** [comment]
I started a build to see if the old code we had works

**Comment by i5o** [comment]
https://travis-ci.org/treehouses/builder/builds/553968225

**Comment by i5o** [comment]
this seems to work:
https://travis-ci.org/treehouses/builder/builds/553968225#L2324
