### ISSUE TITLE
Buster: Problem when attached to HDMI with screen detection

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#451]

**Comment by sc4773rm1nd** [comment]
Buster internal v7 with RPi 4 1gb. 
Boot sequence was displaying fine at native resolution. Desktop not showing.
Crude way to bypass: uncomment "hdmi-group=1" and "hdmi-mode=1" section in /boot/config.txt
Boot process is showing on VGA, but then when in desktop it autodetects the correct resolution.

**Comment by dogi** [comment]
@sc4773rm1nd thx
