### ISSUE TITLE
docker broken on rpi0w

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#476]

**Comment by dogi** [comment]
http://blog.hypriot.com/post/releasing-HypriotOS-1-11/

**Comment by dogi** [comment]
https://github.com/hypriot/rpi-kernel

**Comment by dogi** [comment]
https://github.com/raspberrypi/documentation/blob/master/linux/kernel/building.md

**Comment by CalebProvost** [comment]
Resolved
