### ISSUE TITLE
Open up USB port for connection

### ISSUE THREAD

**Issue by kylemathias** [treehouses/builder#6]
vi /etc/network/interfaces

```allow-hotplug usb0
iface usb0 inet dhcp ```

**Comment by dogi** [comment]
https://learn.adafruit.com/turning-your-raspberry-pi-zero-into-a-usb-gadget/ethernet-gadget

**Comment by 0xdaf** [comment]
I pushed some code to do this to the g_ether branch (see de62c8d).
