### ISSUE TITLE
add package sl

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#622]
![image](https://user-images.githubusercontent.com/13684059/72296657-2bd20f80-3628-11ea-8801-9570e731c1d9.png)

you may have to add enhance the PATH

**Comment by dogi** [comment]
```
$ which sl
/usr/games/sl
```

**Comment by jamjakpa** [comment]
> ```
> $ which sl
> /usr/games/sl
> ```

**Comment by jamjakpa** [comment]
> ```
> $ which sl
> /usr/games/sl
> ```

@dogi can you give me more hints please

**Comment by jamjakpa** [comment]
I am stuck

**Comment by dogi** [comment]
`ln -sr /usr/games/sl /usr/local/bin/sl`

**Comment by jamjakpa** [comment]
![image](https://user-images.githubusercontent.com/44546990/72741413-6eca4080-3b5c-11ea-85a3-361abdf7a925.png)

**Comment by jamjakpa** [comment]
![image](https://user-images.githubusercontent.com/44546990/72741493-99b49480-3b5c-11ea-8b9b-10b0ffdcca55.png)

**Comment by jamjakpa** [comment]
![image](https://user-images.githubusercontent.com/44546990/72741570-c5d01580-3b5c-11ea-85aa-52b912129063.png)

**Comment by jamjakpa** [comment]
![Screenshot from 2020-01-20 08-13-28](https://user-images.githubusercontent.com/44546990/72741636-e4361100-3b5c-11ea-852d-c71d9f28e05d.png)

**Comment by jamjakpa** [comment]
the filename is `32_sl.sh` <----create filename name of the scripts.

**Comment by jamjakpa** [comment]
> `ln -sr /usr/games/sl /usr/local/bin/sl`

hi @dogi, I have created a new branch 'jamjakpa-image-sl1' , in that branch I have build the script and called it 32_sl.sh . I have also created a Release name in Gitbash: 
git pull 
git tag 
git tag release-image-sl1 

somehow i can't see the tag ? in builder
