### ISSUE TITLE
remove this hub-ctrl.c file form root folder

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#636]
![image](https://user-images.githubusercontent.com/13684059/74391558-9070bd80-4dd2-11ea-8c90-d4314e2d4dad.png)

**Comment by dogi** [comment]
https://github.com/treehouses/builder/blob/master/scripts.d/33_usb.sh

**Comment by jamjakpa** [comment]
@dogi , do you want me to remove the file with chmod and ( rm -f ) it from my RPI ?
