### ISSUE TITLE
update 30_ssh_keys.py to python3

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/builder#684]

**Comment by jayala-29** [comment]
should this be what's on the API webpage?

<img width="919" alt="Screen Shot 2020-05-11 at 11 29 11 AM" src="https://user-images.githubusercontent.com/18255250/81597540-bfb7ac00-937a-11ea-9491-146e5a2bfd4d.png">

**Comment by jayala-29** [comment]
nvm, fixed it
