### ISSUE TITLE
Github Actions needs to stop after `Build Successful; no release`

### ISSUE THREAD

**Issue by JLKwong** [treehouses/builder#865]
It still makes the index file:

https://github.com/treehouses/builder/runs/2587824637?check_suite_focus=true#step:6:37

**Comment by rjpadilla** [comment]
This may help??
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-3

**Comment by JLKwong** [comment]
> This may help??
> [docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-3](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-3)

@dogi Would this help? The `Release` step was successful, but maybe there's a way to make it return an error exit code?

**Comment by JLKwong** [comment]
https://github.com/treehouses/builder/runs/2587824637?check_suite_focus=true#step:5:3581
